import '../textobject/textobject';
import './base';
import './motion';
import './operator';

// commands
import './commands/actions';
import './commands/commandLine';
import './commands/digraphs';
import './commands/documentChange';
import './commands/file';
import './commands/fold';
import './commands/incrementDecrement';
import './commands/insert';
import './commands/join';
import './commands/macro';
import './commands/navigate';
import './commands/put';
import './commands/replace';
import './commands/scroll';
import './commands/search';
import './commands/undo';
import './commands/visual';
import './commands/window';
